ALTER TABLE SALESPEOPLE ADD PRIMARY KEY (Snum); 
ALTER TABLE CUSTOMERS ADD PRIMARY KEY (Cnum); 
ALTER TABLE ORDERS ADD PRIMARY KEY (Onum);


ALTER TABLE CUSTOMERS ADD FOREIGN KEY (Snum) REFERENCES SALESPEOPLE(Snum);  
ALTER TABLE ORDERS ADD FOREIGN KEY (Cnum) REFERENCES CUSTOMERS(Cnum);  
ALTER TABLE ORDERS ADD FOREIGN KEY (Snum) REFERENCES SALESPEOPLE(Snum);  




1.
SELECT ORDERS.Onum, CUSTOMERS.Cnum FROM ORDERS, CUSTOMERS WHERE ORDERS.Cnum = CUSTOMERS.Cnum; 

2.
SELECT Sname, Cname, Onum FROM ORDERS, CUSTOMERS, SALESPEOPLE 
WHERE ORDERS.Snum=CUSTOMERS.Snum
  AND ORDERS.Snum=SALESPEOPLE.Snum;

3.
SELECT Cname, Snum, Comm*100 "Commission Rate"
FROM CUSTOMERS
JOIN SALESPEOPLE USING (Snum)
WHERE Comm>.12;

4.
SELECT Amt, Comm FROM SALESPEOPLE JOIN CUSTOMERS USING (Snum)
JOIN ORDERS USING(Snum) WHERE Rating>100;